name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./WebApplicationMVC/WebApplicationMVC.csproj

    - name: Build
      run: dotnet build ./WebApplicationMVC/WebApplicationMVC.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./WebApplicationMVC/WebApplicationMVC.csproj -c Release -o publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: webapp-mvc-gpgsfscwaveehtcd
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ./publish
