name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore C:\Users\USER\source\repos\WebApplication_MVC_CRUD\WebApplication_MVC_CRUD/WebApplication_MVC_CRUD.csproj

    - name: Build
      run: dotnet build C:\Users\USER\source\repos\WebApplication_MVC_CRUD\WebApplication_MVC_CRUD/WebApplication_MVC_CRUD.csproj--configuration Release --no-restore

    - name: Publish
      run: dotnet publish C:\Users\USER\source\repos\WebApplication_MVC_CRUD\WebApplication_MVC_CRUD/WebApplication_MVC_CRUD.csproj -c Release -o publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: webapp-mvc-gpgsfscwaveehtcd
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ./publish
